#!/bin/bash
 
if ["$1" == ""]
then
        echo "type the network like 10.10.10"
else
for ip in {1..254};
do

hping3 -S -p 13 -c 1 $1.$ip;hping3 -S -p 37 -c 1 $1.$ip;hping3 -S -p 30000 -c 1 $1.$ip;hping3 -S -p 3000 -c 1 $1.$ip;hping3 -S -p 1337 -c1 $1.$ip 2> /dev/null | grep "flags=SA" | cut -d " " -f 2 | cut -d "=" -f2;

#As you can see, I wasnt able to create an automation so that it would stop after finding the target port
#Neither added a simple > <filename>, so the final result would be printed in a file. This is easy.
#Below is what I can imagine but still can not reason logically into a code.

#       if [x =="flag=SA"]
#       then stop
#       else cntl C
#       fi


done
fi
